In [1]:
import pandas as p

In [2]:
#simple linear regression

In [3]:
import numpy as n

In [4]:
d={"no of rooms":[1,2,3,4,5],"cost":[100,200,300,400,500]}
df=p.DataFrame(d)
df

no of rooms  cost
0            1   100
1            2   200
2            3   300
3            4   400
4            5   500

In [5]:
### scikit-learn or sklearn:

In [8]:
from sklearn.linear_model import LinearRegression as l
obj=l()
obj

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [9]:
x=df[["no of rooms"]]
y=df["cost"]

In [10]:
obj.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
obj.predict([[100*10]])

array([100000.])

In [28]:
pre=n.array([7,6,7]).reshape(-1,1)
obj.predict(pre)


array([700., 600., 700.])

In [25]:
obj.predict(x)

array([100., 200., 300., 400., 500.])

In [27]:
obj.score(x,y)*100

100.0

In [31]:
pre_y=obj.predict(x)
from sklearn.metrics import r2_score as a
a(pre_y,y)

1.0